# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://gerhean.netlify.app/"
DefaultContentLanguage  = "en"
title                   = "Ger Hean Blog"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default", "/css/stip.css"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  #socialShare           = ["linkedin", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    author              = "Ger Hean"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Home"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Ger Hean's Whimsical Thoughts"
    paragraph             = "Writing about random stuff!"
    rssIntro              = false
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/portrait.jpg"
      shape               = "circle"
      width               = ""
      alt                 = "My Portrait"

  [params.sidebar]
    about               = "Self proclaimed genius software engineer."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = false
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = "github"
    username            = "gerhean"
    repo                = "gerhean_hugo_site"
    branch              = "live-site"

    [params.staticman.recaptcha]
      siteKey           = "6LeB_v0ZAAAAANs1pfw9WMDl6T7EQ9JvXqeSqq-A"
      encryptedKey      = "StBjRDsqq6t/UASOIN0REKvgF52pnN3DteF1il5OQ2AuMs1VeYKsdykXX9fXTfqiByYB+NDXVZ6pMQEDk9tyxpdQQio+Mq9oznzS0JngUxg5SUx3dpbMM+Shgef8kfSJw1n3nYAVy/IEjcXhc32dmF0wA6IcjyTF4nsH1WuEbpqZ+D8axR9+iUGFkJg5BMOJ9gAWtdJ9MDCTCNDFFRG6GAN9i11eHMF7hZLz2wMIpf7NIib/ib0c6UAaKmBROU3X0IQ3ziKu1dyChIWVhf+TVdhtMsJqVdtognYu+51GTZEhHXVuQPXJRY034Ta64qUIEeYRlrv37yxdapZPLxEm0g=="

    # For Homepage
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "gerhean@live.com"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/gerhean"

    [[params.links]]
        icon = "linkedin"
        title = "Linkedin"
        url = "https://www.linkedin.com/in/gerhean/"

    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://www.instagram.com/gerhean/"

#    [[params.links]]
#        icon = "twitter"
#        title = "Twitter"
#        url = "https://twitter.com/"

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6
  
  [[menu.main]]
    name              = "Source"
    identifier        = "gsource"
    url               = "https://github.com/gerhean/gerhean_hugo_site"
    pre               = "<i class='fab fa-github'></i>"
    weight            = 7

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1


[social]
  # Coding Communities
  github                = "https://github.com/gerhean"
  #gitlab                = ""
  #stackoverflow         = "" # User Number
  #bitbucket             = ""
  #jsfiddle              = ""
  #codepen               = ""
  
  # Visual Art Communities
  #deviantart            = ""
  #flickr                = "example"
  #behance               = ""
  #dribbble              = ""
  
  # Publishing Communities
  #wordpress             = ""
  #medium                = ""
  
  # Professional/Business Oriented Communities
  linkedin              = "https://www.linkedin.com/in/gerhean/"
  #linkedin_company      = "examplebusiness"
  #foursquare            = ""
  #xing                  = ""
  #slideshare            = ""
  
  # Social Networks
  #facebook              = "example"
  #googleplus            = ""
  #reddit                = "example"
  #quora                 = ""
  #youtube               = ""
  #vimeo                 = ""
  #whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    #wechat              = ""
    #qq                  = "" # User ID Number
  instagram             = "gerhean"
  #tumblr                = ""
  #twitter               = "example"
  #strava                = ""
  #skype                 = ""
  #snapchat              = ""
  #pinterest             = "example"
  telegram              = "gerhean"
  #vine                  = ""
  #googlescholar         = ""
  #orcid                 = ""
  #researchgate          = "example"
  #keybase               = "example"
  #mastodon              = "example.com/@example"

  # Email
  email                 = "gerhean@live.com"

